#!/usr/bin/python

#    MaxiCom -- A serial port terminal emulator for the GNOME desktop.
#    Copyright (C) 2010  Gareth McMullin
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

version = sys.version_info
if (version[0] < 2) or (version[1] < 6):
	print("Sorry, MaxiCom requires Python 2.6")
	exit(-1)

if version[0] >= 3:
	print("Sorry, MaxiCom is not yet ported to Python 3")
	exit(-1)
	
import maxicom

maxicom.main()

